const allQuestions = [
    [span_0](start_span){ q: "1) Что является целью изучения дисциплины «Алгоритмизация и программирование»?[span_0](end_span)[span_1](start_span)", o: ["является изучение теоретических основ программирования и приобретение навыков разработки алгоритмов решения задач, и перевода их в программы[span_1](end_span)[span_2](start_span)", "является изучение артефактов, связанных со сбором, хранением, передачей, обработкой данных средствами вычислительной техники[span_2](end_span)"], a: 0 },
    [span_3](start_span){ q: "2) Какой язык называется языком программирования?[span_3](end_span)[span_4](start_span)", o: ["формальный язык, предназначенный для записи компьютерных программ;[span_4](end_span)[span_5](start_span)", "естественный разговорный язык, на котором люди общаются между собой.[span_5](end_span)"], a: 0 },
    [span_6](start_span){ q: "3) Какими из перечисленных свойств должен обладать алгоритм?[span_6](end_span)[span_7](start_span)", o: ["дискретность и конечность[span_7](end_span)[span_8](start_span)", "только простата[span_8](end_span)"], a: 0 },
    [span_9](start_span){ q: "4) Что такое компьютер?[span_9](end_span)[span_10](start_span)", o: ["программно управляемое электронное устройство для обработки информации;[span_10](end_span)[span_11](start_span)", "электронное устройство, предназначенное для автоматизации процессов сбора, хранения, передачи и обработки данных и работающее под управлением программ;[span_11](end_span)[span_12](start_span)", "технически сложное устройство, работающее под управлением человека и предназначенное для арифметических операций.[span_12](end_span)"], a: 1 },
    [span_13](start_span){ q: "5) Теоретической основой структурного программирования принято считать:[span_13](end_span)[span_14](start_span)", o: ["принципы, изложенные в классической работе Коррадо Бома и Джузеппе Джакопини (1965);[span_14](end_span)", "структурную теорему Э. [span_15](start_span)Дейкстры «Алгоритм решения любой задачи может быть построен с использованием только трех типов вычислительных структур...»[span_15](end_span)[span_16](start_span)", "языки программирования высокого уровня.[span_16](end_span)"], a: 0 },
    [span_17](start_span){ q: "6) Структурное программирование[span_17](end_span)[span_18](start_span)", o: ["разрешает использование оператора безусловного перехода GOTO.[span_18](end_span)[span_19](start_span)", "запрещает использование произвольных переходов к метке, за счет чего программа приобретает более упорядоченный характер.[span_19](end_span)"], a: 1 },
    [span_20](start_span){ q: "7) Согласно ГОСТ 19.701-90 блоком начала/конца (овал)[span_20](end_span)[span_21](start_span)", o: ["начинается и заканчивается любая процедура, функция;[span_21](end_span)[span_22](start_span)", "из блока всегда выходит стрелка управления.[span_22](end_span)[span_23](start_span)", "тип возвращаемого значения и аргументов функции обычно указывается в комментариях к блоку.[span_23](end_span)"], a: 0 },
    [span_24](start_span){ q: "8) Согласно ГОСТ 19.701-90 блок-соединитель (круг) используется[span_24](end_span)[span_25](start_span)", o: ["если блок-схема не умещается на листе;[span_25](end_span)[span_26](start_span)", "отражает переход потока управления между листами;[span_26](end_span)[span_27](start_span)", "не отражает переход потока управления.[span_27](end_span)"], a: 0 },
    [span_28](start_span){ q: "9) Что такое алгоритм?[span_28](end_span)[span_29](start_span)", o: ["это набор действий, реализация которых может привести к решению задачи;[span_29](end_span)[span_30](start_span)", "это понятный исполнителю набор правил для решения конкретного множества задач...[span_30](end_span)[span_31](start_span)", "это чётко определённая последовательность действий или инструкций, предназначенная для решения определённой задачи или класса задач.[span_31](end_span)"], a: 2 },
    [span_32](start_span){ q: "10) Согласно ГОСТ 19.701-90 Операции ввода/вывода данных (параллелограмм)[span_32](end_span)[span_33](start_span)", o: ["определяется множество символов ввода/вывода, например вывод на дисплеи...[span_33](end_span)[span_34](start_span)", "если источник данных не принципиален, обычно используется символ параллелограмма;[span_34](end_span)[span_35](start_span)", "подробности ввода/вывода не могут быть указаны в комментариях.[span_35](end_span)"], a: 1 },
    [span_36](start_span){ q: "11) Какие вычислительные структуры могут входить в алгоритмы решения задач?[span_36](end_span)[span_37](start_span)", o: ["ветвления, цикла, линейная[span_37](end_span)[span_38](start_span)", "только разворота[span_38](end_span)"], a: 0 },
    [span_39](start_span){ q: "12) Что такое операционная система?[span_39](end_span)[span_40](start_span)", o: ["совокупность системных и служебных программ, обеспечивающих доступ пользователя ко всем ресурсам компьютера;[span_40](end_span)[span_41](start_span)", "программа, предназначенная для решения практической задачи пользователя;[span_41](end_span)[span_42](start_span)", "программа, предназначенная для перевода программы пользователя...[span_42](end_span)"], a: 0 },
    [span_43](start_span){ q: "13) Согласно ГОСТ 19.701-90 Вызов внешней процедуры[span_43](end_span)[span_44](start_span)", o: ["вызов внешних процедур и функций помещается в прямоугольник с дополнительными вертикальными линиями.[span_44](end_span)[span_45](start_span)", "вызов внешних процедур помещается в прямоугольник с дополнительными горизонтальными сторонами.[span_45](end_span)"], a: 0 },
    [span_46](start_span){ q: "14) Согласно ГОСТ 19.701-90 в Блоке операций (прямоугольник)[span_46](end_span)[span_47](start_span)", o: ["обычно размещают одну или несколько операций присваивания, не требующих вызова внешних функций;[span_47](end_span)[span_48](start_span)", "обычно размещают одну или несколько операций присваивания, требующих вызова внешних функций.[span_48](end_span)"], a: 0 },
    [span_49](start_span){ q: "15) Согласно ГОСТ 19.701-90 Блок, иллюстрирующий ветвление алгоритма (ромб) – это[span_49](end_span)[span_50](start_span)", o: ["блок в виде ромба имеет один вход и несколько подписанных выходов;[span_50](end_span)[span_51](start_span)", "блок в виде ромба имеет один вход и один подписанный выход;[span_51](end_span)[span_52](start_span)", "в случае, если блок имеет 2 выхода (соответствует оператору ветвления), на них подписывается результат сравнения — «да/нет».[span_52](end_span)"], a: 2 },
    { q: "16) Современное формальное определение алгоритма было дано в 30 - 50-х гг. [span_53](start_span)XX века в работах математиков:[span_53](end_span)[span_54](start_span)", o: ["Алана Тьюринга, Эмиля Леона Поста, Алонзо Чёрча[span_54](end_span)[span_55](start_span)", "Норберта Винера, Пафнутия Львовича Чебышева[span_55](end_span)"], a: 0 },
    [span_56](start_span){ q: "17) Какими из перечисленных свойств должен обладать правильно составленный алгоритм решения любой задачи?[span_56](end_span)[span_57](start_span)", o: ["конечность, эффективность, понятность, результативность, дискретность[span_57](end_span)[span_58](start_span)", "только дискретность[span_58](end_span)"], a: 0 },
    [span_59](start_span){ q: "18) Процесс создания информационной системы - это[span_59](end_span)[span_60](start_span)", o: ["разработка спецификации программного обеспечения[span_60](end_span)[span_61](start_span)", "эволюция ПО[span_61](end_span)[span_62](start_span)[span_63](start_span)[span_64](start_span)", "все, кроме эволюции ПО (разработка спецификации, проектирование, реализация, аттестация, внедрение)[span_62](end_span)[span_63](end_span)[span_64](end_span)"], a: 2 },
    [span_65](start_span){ q: "19) Процедурное программирование – это[span_65](end_span)[span_66](start_span)", o: ["только возможность повторного использования кода;[span_66](end_span)[span_67](start_span)", "принцип заключается в разбиении сложной задачи на менее сложные подзадачи...[span_67](end_span)"], a: 1 },
    [span_68](start_span){ q: "20) Что такое оператор в программе, написанной на алгоритмическом языке программирования?[span_68](end_span)[span_69](start_span)", o: ["конструкция языка, реализующая какое-то законченное действие;[span_69](end_span)[span_70](start_span)", "конструкция языка определяющее определенное условие;[span_70](end_span)[span_71](start_span)", "ничего из вышеперечисленного.[span_71](end_span)"], a: 0 },
    [span_72](start_span){ q: "21) Примером декларативного подхода к программированию являются языки семейства:[span_72](end_span)[span_73](start_span)", o: ["SQL – языки запросов к базам данных...[span_73](end_span)[span_74](start_span)", "BASIC – язык алгоритмического программирования высокого уровня.[span_74](end_span)"], a: 0 },
    [span_75](start_span){ q: "22) Преимущества визуального представления программы перед текстовым:[span_75](end_span)[span_76](start_span)", o: ["высокая наглядность и удобство для человека;[span_76](end_span)[span_77](start_span)", "все вышеперечисленное (высокая наглядность, сокращение трудоемкости, повышение качества).[span_77](end_span)"], a: 1 },
    { q: "23) Первым программистом аналитической машины Ч. [span_78](start_span)Бэббиджа, который составил предписание по расчету чисел Бернулли, является:[span_78](end_span)[span_79](start_span)", o: ["леди Ада Лавлейс;[span_79](end_span)[span_80](start_span)", "Якоб Бернулли;[span_80](end_span)[span_81](start_span)", "Чарльз Бэббидж.[span_81](end_span)"], a: 0 },
    [span_82](start_span){ q: "24) Основная цель алгоритмизации – это[span_82](end_span)[span_83](start_span)", o: ["составление алгоритмов для электронно-вычислительной машины с дальнейшим решением задачи на компьютере;[span_83](end_span)[span_84](start_span)", "написание программного кода для решения производственной задачи на компьютере;[span_84](end_span)[span_85](start_span)", "создание библиотеки или приложения...[span_85](end_span)"], a: 0 },
    [span_86](start_span){ q: "25) Назовите типы циклических структур:[span_86](end_span)[span_87](start_span)", o: ["циклическая структура со счётчиком, с предусловием, с постусловием[span_87](end_span)[span_88](start_span)", "циклическая структура в цикле.[span_88](end_span)"], a: 0 },
    [span_89](start_span){ q: "26) Какими основными свойствами обладает алгоритм?[span_89](end_span)[span_90](start_span)", o: ["только дистрибутивность[span_90](end_span)[span_91](start_span)", "эффективность, определенность, конечность[span_91](end_span)"], a: 1 },
    [span_92](start_span){ q: "27) Какие из перечисленных форм представления алгоритма используются при составлении блок-схем?[span_92](end_span)[span_93](start_span)", o: ["словесная, программная[span_93](end_span)[span_94](start_span)", "графическая[span_94](end_span)"], a: 1 },
    [span_95](start_span){ q: "28) Какие из перечисленных видов алгоритмов соответствуют циклическому алгоритму?[span_95](end_span)[span_96](start_span)", o: ["алгоритм, содержащий хотя бы одну проверку условия, в результате которой выполняется либо одна, либо другая последовательность...[span_96](end_span)[span_97](start_span)", "алгоритм, предусматривающий многократное повторение одной и той же последовательности действий...[span_97](end_span)"], a: 1 },
    [span_98](start_span){ q: "29) Какие из перечисленных видов алгоритмов соответствуют разветвляющемуся алгоритму?[span_98](end_span)[span_99](start_span)", o: ["алгоритм, содержащий хотя бы одну проверку условия, в результате которой выполняется либо одна, либо другая последовательность действий;[span_99](end_span)[span_100](start_span)", "алгоритм, предусматривающий многократное повторение...[span_100](end_span)"], a: 0 },
    [span_101](start_span){ q: "30) Какие из перечисленных видов алгоритмов соответствуют линейному алгоритму?[span_101](end_span)[span_102](start_span)", o: ["это алгоритм, в котором действия выполняются однократно и строго последовательно.[span_102](end_span)[span_103](start_span)", "алгоритм, содержащий хотя бы одну проверку условия...[span_103](end_span)"], a: 0 },
    [span_104](start_span){ q: "31) Информационная система (ИС) — это[span_104](end_span)[span_105](start_span)", o: ["система, предназначенная для хранения, поиска и обработки информации, и соответствующие организационные ресурсы... (ISO/IEC 2382:2015);[span_105](end_span)[span_106](start_span)", "программное обеспечение (программная система), реализующее деловую стратегию организации.[span_106](end_span)"], a: 0 },
    [span_107](start_span){ q: "32) Что такое файл?[span_107](end_span)[span_108](start_span)", o: ["поименованный участок электронного носителя данных, где в том или ином формате хранятся данные;[span_108](end_span)[span_109](start_span)", "information processing;[span_109](end_span)[span_110](start_span)", "documentation symbols and conventions...[span_110](end_span)"], a: 0 },
    [span_111](start_span){ q: "33) Идея визуального (графического) программирования сводится к тому, что[span_111](end_span)[span_112](start_span)", o: ["написание программы как текста заменяется в том или ином масштабе ее изображением...[span_112](end_span)[span_113](start_span)", "реализуется тенденция к развитию средств, позволяющих программисту при создании программы оперировать не текстовыми, синтаксическими конструкциями, а графическими образами;[span_113](end_span)"], a: 1 },
    [span_114](start_span){ q: "34) Выберете из предложенных верное определение алгоритма:[span_114](end_span)[span_115](start_span)", o: ["десятичная позиционная система счисления и искусство счета в ней;[span_115](end_span)[span_116](start_span)", "точное описание, которое задаёт вычислительный процесс, начинающийся с произвольного исходного данного и направленный на получение результата;[span_116](end_span)"], a: 1 },
    [span_117](start_span){ q: "35) Выберете верные утверждения:[span_117](end_span)[span_118](start_span)", o: ["блок-схема – это графическая реализация алгоритма;[span_118](end_span)[span_119](start_span)", "блок-схема представляет собой удобный и наглядный способ записи алгоритма;[span_119](end_span)[span_120](start_span)[span_121](start_span)", "верно 1 и 2.[span_120](end_span)[span_121](end_span)"], a: 2 },
    [span_122](start_span){ q: "36) Выберете верную классификацию структур данных:[span_122](end_span)[span_123](start_span)", o: ["простые базовые, статические, полустатические, динамические, файловые[span_123](end_span)[span_124](start_span)", "только серверные[span_124](end_span)"], a: 0 },
    [span_125](start_span){ q: "37) Что понимается под объектом в языке программирования VBA?[span_125](end_span)[span_126](start_span)", o: ["это сущность, с которой нельзя взаимодействовать;[span_126](end_span)[span_127](start_span)", "это любая сущность, с которой можно взаимодействовать.[span_127](end_span)"], a: 1 },
    [span_128](start_span){ q: "38) В средневековой Европе алгоритмом называлась[span_128](end_span)[span_129](start_span)", o: ["десятичная позиционная система счисления и искусство счета в ней;[span_129](end_span)[span_130](start_span)", "последовательность математических действий в алгебраических расчётах;[span_130](end_span)"], a: 0 },
    [span_131](start_span){ q: "39) В Российской Федерации действует[span_131](end_span)[span_132](start_span)", o: ["ГОСТ 19.701-90 «Схемы алгоритмов программ, данных и систем»;[span_132](end_span)[span_133](start_span)", "ГОСТ 19.701-90 «Схемы программ, данных и систем»;[span_133](end_span)"], a: 0 },
    [span_134](start_span){ q: "40) Верно ли высказывание: «Процедура — блок, который раскрывается в другом месте, а из данной программы лишь вызывается (указанием ее имени)»?[span_134](end_span)[span_135](start_span)", o: ["да;[span_135](end_span)[span_136](start_span)", "нет.[span_136](end_span)"], a: 0 },
    [span_137](start_span){ q: "41) Что такое оператор в языке программирования VBA?[span_137](end_span)[span_138](start_span)", o: ["это конструкция языка, определяющая какое-то законченное действие;[span_138](end_span)[span_139](start_span)", "это конструкция языка, изменяющая свое значение в ходе выполнения программы.[span_139](end_span)"], a: 0 },
    [span_140](start_span){ q: "42) Что такое процессор?[span_140](end_span)[span_141](start_span)", o: ["является центральным вычислительным элементом (мозгом) любого компьютера, управляет всеми остальными его элементами;[span_141](end_span)[span_142](start_span)", "устройство для хранения программ и данных[span_142](end_span)"], a: 0 },
    [span_143](start_span){ q: "43) В 1938 году немецкий инженер Конрад Цузе построил первую вычислительную электромеханическую машину... а в 1945 году разработал язык:[span_143](end_span)[span_144](start_span)", o: ["Plankalkül (Планкалкюль);[span_144](end_span)[span_145](start_span)", "ALGOL (Алгол);[span_145](end_span)"], a: 0 },
    [span_146](start_span){ q: "44) Благодаря латинскому переводу трактата Аль-Хорезми Algoritmi de numero Indorum... в XII веке Европа познакомилась с позиционной системой счисления, разработанной:[span_146](end_span)[span_147](start_span)", o: ["в Индии;[span_147](end_span)[span_148](start_span)", "в Иране;[span_148](end_span)[span_149](start_span)", "в Греции.[span_149](end_span)"], a: 0 },
    [span_150](start_span){ q: "45) На какие классы делится программное обеспечение компьютера?[span_150](end_span)[span_151](start_span)", o: ["системное, прикладное, инструментальное[span_151](end_span)[span_152](start_span)", "только пользовательское[span_152](end_span)"], a: 0 },
    [span_153](start_span){ q: "46) Персидский ученый Абу Абдуллах Мухаммад ибн Муса аль-Хорезми в IX веке в книге «Китаб аль-джебр валь-мукабала» изложил:[span_153](end_span)[span_154](start_span)", o: ["описание придуманной в Индии позиционной десятичной системы счисления;[span_154](end_span)[span_155](start_span)", "впервые использовал цифру 0...[span_155](end_span)"], a: 0 },
    [span_156](start_span){ q: "47) Аналитическая машина Чарльза Бэббиджа (1830г.) была[span_156](end_span)[span_157](start_span)", o: ["первым счётным устройством;[span_157](end_span)[span_158](start_span)", "первым программируемым счетным устройством;[span_158](end_span)[span_159](start_span)", "первым механическим устройством для автоматизации счёта.[span_159](end_span)"], a: 1 },
    [span_160](start_span){ q: "48) Автор книги «Программы = Алгоритмы + Структуры»[span_160](end_span)[span_161](start_span)", o: ["Никлаус Вирт;[span_161](end_span)[span_162](start_span)", "Дональд Эрвин Кнут;[span_162](end_span)"], a: 0 },
    [span_163](start_span){ q: "49) Определите вид выделенной алгоритмической структуры (последовательное выполнение Команда 1 -> Команда 2)?[span_163](end_span)[span_164](start_span)", o: ["линейная;[span_164](end_span)[span_165](start_span)", "ветвящаяся;[span_165](end_span)[span_166](start_span)", "циклическая.[span_166](end_span)"], a: 0 },
    [span_167](start_span){ q: "50) Язык программирования VBA является:[span_167](end_span)[span_168](start_span)", o: ["предметно-ориентированным языком программирования;[span_168](end_span)[span_169](start_span)", "структурно-ориентированным языком программирования;[span_169](end_span)[span_170](start_span)", "объектно-ориентированным языком программирования.[span_170](end_span)"], a: 2 },
    [span_171](start_span){ q: "51) Какое значение будет выведено на экран монитора после выполнения фрагмента VBA:\nX=3\nY=5.5\nIf x > y or x < 5 then z = 2 else z = 3\nMsgbox z[span_171](end_span)[span_172](start_span)", o: ["4[span_172](end_span)[span_173](start_span)", "2[span_173](end_span)[span_174](start_span)", "3[span_174](end_span)"], a: 1 },
    [span_175](start_span){ q: "52) Какое значение будет выведено:\nZ=5\nX=3\nY=5.5\nIf x > y or x < 5 then z = 2 else z = 3\nEnd if\nMsgbox z[span_175](end_span)[span_176](start_span)", o: ["4[span_176](end_span)[span_177](start_span)", "2[span_177](end_span)[span_178](start_span)", "3[span_178](end_span)"], a: 1 },
    [span_179](start_span){ q: "53) Какое значение будет выведено:\nZ=7\nX=3\nY=5.5\nIf x > y and x < 5 then z = 2 end if\nMsgbox z[span_179](end_span)[span_180](start_span)", o: ["7[span_180](end_span)[span_181](start_span)", "2[span_181](end_span)[span_182](start_span)", "3[span_182](end_span)"], a: 0 },
    [span_183](start_span){ q: "54) Какое значение будет выведено:\nZ=5\nX=3\nY=5.5\nIf x > y and x < 5 then z = 2 else z = 4\nend if\nMsgbox z[span_183](end_span)[span_184](start_span)", o: ["4[span_184](end_span)[span_185](start_span)", "2[span_185](end_span)[span_186](start_span)", "3[span_186](end_span)"], a: 0 },
    [span_187](start_span){ q: "55) Какое значение будет выведено:\nx=3\nY=5.5\nIf x > y or x < 5 then z = x + y else z = x - y\nMsgbox z[span_187](end_span)[span_188](start_span)", o: ["8.5[span_188](end_span)[span_189](start_span)", "-2.5[span_189](end_span)[span_190](start_span)", "9[span_190](end_span)"], a: 0 },
    [span_191](start_span){ q: "56) Какое значение будет выведено:\nZ=5, x=3, Y=5.5\nFor k=1 to 10 step 2\nY=y + 1\nNext k\nMsgbox z[span_191](end_span)[span_192](start_span)", o: ["5[span_192](end_span)[span_193](start_span)", "10.5[span_193](end_span)[span_194](start_span)", "8[span_194](end_span)"], a: 0 },
    [span_195](start_span){ q: "57) Какое значение будет выведено:\nZ=5, x=3, Y=5.5\nFor k=1 to 10 step 2\nZ = y + 1\nNext k\nMsgbox z[span_195](end_span)[span_196](start_span)", o: ["8.5[span_196](end_span)[span_197](start_span)", "6.5[span_197](end_span)[span_198](start_span)", "7[span_198](end_span)"], a: 1 },
    [span_199](start_span){ q: "58) Какое значение будет выведено:\nZ=5, x=3, Y=5.4\nFor k=1 to 10 step 2\nZ = y + 1\nNext k\nMsgbox z[span_199](end_span)[span_200](start_span)", o: ["6.4[span_200](end_span)[span_201](start_span)", "-2.4[span_201](end_span)[span_202](start_span)", "6[span_202](end_span)"], a: 0 },
    [span_203](start_span){ q: "59) Какое значение будет выведено:\nZ=5, x=3, Y=5.5\nFor k=1 to 10 step 2\nZ = z + 1\nNext k\nMsgbox z[span_203](end_span)[span_204](start_span)", o: ["8.5[span_204](end_span)[span_205](start_span)", "-2.5[span_205](end_span)[span_206](start_span)", "10[span_206](end_span)"], a: 2 },
    [span_207](start_span){ q: "60) Какое значение будет выведено:\nZ=5, x=3, Y=5.5, K=1\nFor k=1 to 10 step 2\nZ = z + K\nNext k\nMsgbox z[span_207](end_span)[span_208](start_span)", o: ["10[span_208](end_span)[span_209](start_span)", "11[span_209](end_span)[span_210](start_span)", "30[span_210](end_span)"], a: 2 },
    [span_211](start_span){ q: "61) Какое значение будет выведено:\nZ=5, x=3, Y=5.5, K=1\nWhile k <= 10\nZ = z + K\nk=k+1\nWend\nMsgbox z[span_211](end_span)[span_212](start_span)", o: ["31[span_212](end_span)[span_213](start_span)", "29[span_213](end_span)[span_214](start_span)", "60[span_214](end_span)"], a: 2 },
    [span_215](start_span){ q: "62) Что такое компьютерная сеть?[span_215](end_span)[span_216](start_span)", o: ["комплекс компьютерного оборудования;[span_216](end_span)[span_217](start_span)", "компьютеры, связанные системой передачи данных;[span_217](end_span)[span_218](start_span)", "компьютеры, соединенные линиями связи.[span_218](end_span)"], a: 1 },
    [span_219](start_span){ q: "63) В чем отличие подпрограммы-процедуры от подпрограммы-функции в VBA?[span_219](end_span)[span_220](start_span)", o: ["в операторах заголовках и операторах окончаниях;[span_220](end_span)[span_221](start_span)", "в количестве возвращаемых из них значений (функция возвращает значение);[span_221](end_span)[span_222](start_span)", "никаких принципиальных отличий у них нет.[span_222](end_span)"], a: 1 },
    [span_223](start_span){ q: "64) Что понимается под переменной в VBA?[span_223](end_span)[span_224](start_span)", o: ["конструкция языка, значение которой не изменяется в ходе выполнения программы;[span_224](end_span)[span_225](start_span)", "конструкция языка, значение которой изменяется в ходе выполнения программы;[span_225](end_span)"], a: 1 },
    [span_226](start_span){ q: "65) Какими бывают логические выражения в VBA?[span_226](end_span)[span_227](start_span)", o: ["искусственными и естественными;[span_227](end_span)[span_228](start_span)", "простыми и сложными;[span_228](end_span)"], a: 1 },
    [span_229](start_span){ q: "66) Что такое интерфейс?[span_229](end_span)[span_230](start_span)", o: ["способ взаимодействия[span_230](end_span)[span_231](start_span)", "способ передачи данных[span_231](end_span)[span_232](start_span)", "способ хранения данных[span_232](end_span)"], a: 0 },
    [span_233](start_span){ q: "67) Что понимается под константой в VBA?[span_233](end_span)[span_234](start_span)", o: ["конструкция языка, значение которой не изменяется в ходе выполнения программы[span_234](end_span)[span_235](start_span)", "конструкция языка, значение которой изменяется...[span_235](end_span)"], a: 0 },
    [span_236](start_span){ q: "68) Сколько условных операторов в VBA?[span_236](end_span)[span_237](start_span)", o: ["2 (If и Select Case)[span_237](end_span)[span_238](start_span)", "3[span_238](end_span)[span_239](start_span)", "4[span_239](end_span)"], a: 0 },
    [span_240](start_span){ q: "69) Сколько операторов цикла в VBA?[span_240](end_span)[span_241](start_span)", o: ["2[span_241](end_span)[span_242](start_span)", "3[span_242](end_span)[span_243](start_span)", "4 (For, For Each, Do, While)[span_243](end_span)"], a: 2 },
    [span_244](start_span){ q: "70) В какую структуру организованы объекты в VBA?[span_244](end_span)[span_245](start_span)", o: ["линейную[span_245](end_span)[span_246](start_span)", "сетевую[span_246](end_span)[span_247](start_span)", "иерархическую[span_247](end_span)"], a: 2 },
    [span_248](start_span){ q: "71) Что такое пользовательская форма в VBA?[span_248](end_span)[span_249](start_span)", o: ["это свойство объекта Application[span_249](end_span)[span_250](start_span)", "это объект, представляющий собой контейнер, в котором располагаются элементы управления[span_250](end_span)[span_251](start_span)", "это метод, применяемый к объекту Application[span_251](end_span)"], a: 1 },
    [span_252](start_span){ q: "72) Сколько окон предусмотрено в редакторе VBA?[span_252](end_span)[span_253](start_span)", o: ["5[span_253](end_span)[span_254](start_span)", "7[span_254](end_span)[span_255](start_span)", "9[span_255](end_span)"], a: 1 },
    [span_256](start_span){ q: "73) Какие методы могут быть применены к объекту UserForm?[span_256](end_span)[span_257](start_span)", o: ["select[span_257](end_span)[span_258](start_span)", "show и hide[span_258](end_span)[span_259](start_span)", "clear[span_259](end_span)"], a: 1 },
    [span_260](start_span){ q: "74) Что такое событие в VBA?[span_260](end_span)[span_261](start_span)", o: ["это то, что происходит с программой и может быть ей распознано;[span_261](end_span)[span_262](start_span)", "это то, что происходит с объектом при его удалении;[span_262](end_span)[span_263](start_span)", "передача данных из одного объекта в другой.[span_263](end_span)"], a: 0 },
    [span_264](start_span){ q: "75) Что такое элемент управления?[span_264](end_span)[span_265](start_span)", o: ["это специализированный объект, на котором размещается пользовательская форма;[span_265](end_span)[span_266](start_span)", "это специализированный объект, который можно размещать на пользовательских формах VBA и который используется для организации взаимодействия с пользователем;[span_266](end_span)"], a: 1 },
    [span_267](start_span){ q: "76) Что собой представляет элемент управления Label?[span_267](end_span)[span_268](start_span)", o: ["этот элемент управления позволяет пользователю выбирать \"готовые\" значения из списка...[span_268](end_span)[span_269](start_span)", "это просто область пользовательской формы, в которой выводится какой-то текст;[span_269](end_span)"], a: 1 },
    [span_270](start_span){ q: "77) Что собой представляет элемент TextBox?[span_270](end_span)[span_271](start_span)", o: ["это просто область пользовательской формы, куда вводится или выводится какой-то текст;[span_271](end_span)[span_272](start_span)", "это элемент управления используются для выбора не взаимоисключающих вариантов...[span_272](end_span)"], a: 0 },
    [span_273](start_span){ q: "78) Что собой представляет элемент управления CheckBox?[span_273](end_span)[span_274](start_span)", o: ["это элемент управления используются для выбора не взаимоисключающих вариантов (если этих вариантов немного);[span_274](end_span)[span_275](start_span)", "этот элемент управления позволяет пользователю выбирать \"готовые\" значения из списка...[span_275](end_span)"], a: 0 },
    [span_276](start_span){ q: "79) Что собой представляет элемент управления OptionButton?[span_276](end_span)[span_277](start_span)", o: ["этот элемент управления используется для выбора не взаимоисключающих вариантов...[span_277](end_span)[span_278](start_span)", "этот элемент управления используется для выбора взаимоисключающих вариантов.[span_278](end_span)"], a: 1 },
    [span_279](start_span){ q: "80) Что собой представляет элемент управления Frame?[span_279](end_span)[span_280](start_span)", o: ["это просто рамка, которая выделяет прямоугольную область в пользовательской форме и позволяет организовать элементы управления;[span_280](end_span)[span_281](start_span)", "это просто область пользовательской формы, куда вводится или выводится какой-то текст.[span_281](end_span)"], a: 0 },
    [span_282](start_span){ q: "81) Что собой представляет элемент управления CommandButton?[span_282](end_span)[span_283](start_span)", o: ["это просто область пользовательской формы...[span_283](end_span)[span_284](start_span)", "это кнопка;[span_284](end_span)[span_285](start_span)", "это просто рамка...[span_285](end_span)"], a: 1 },
    [span_286](start_span){ q: "82) Что собой представляет элемент управления ListBox?[span_286](end_span)[span_287](start_span)", o: ["это просто рамка, которая выделяет прямоугольную область...[span_287](end_span)[span_288](start_span)", "это окно, куда выводится список из нескольких наименований, из которых можно выбрать один или несколько.[span_288](end_span)"], a: 1 },
    [span_289](start_span){ q: "83) Что собой представляет элемент управления ScrollBar?[span_289](end_span)[span_290](start_span)", o: ["это полоса прокрутки для быстрого нахождения нужного наименования в длинном списке;[span_290](end_span)[span_291](start_span)", "это просто рамка...[span_291](end_span)"], a: 0 },
    [span_292](start_span){ q: "84) Что собой представляет элемент управления TabStrip?[span_292](end_span)[span_293](start_span)", o: ["используют его для создания набора диалоговых вкладок, отображающих одни и те же данные в различных категориях;[span_293](end_span)[span_294](start_span)", "это полоса прокрутки...[span_294](end_span)"], a: 0 },
    [span_295](start_span){ q: "85) Что собой представляет элемент управления Image?[span_295](end_span)[span_296](start_span)", o: ["это окно, куда выводится список...[span_296](end_span)[span_297](start_span)", "этот элемент управления позволяет отобразить на форме рисунок в одном из распространенных форматов, который будет реагировать на щелчок мышью;[span_297](end_span)"], a: 1 },
    [span_298](start_span){ q: "86) Что собой представляет элемент управления Multipage?[span_298](end_span)[span_299](start_span)", o: ["этот элемент управления позволяет создавать на форме несколько страниц, между которыми сможет переходить пользователь;[span_299](end_span)[span_300](start_span)", "это окно, куда выводится список...[span_300](end_span)"], a: 0 },
    [span_301](start_span){ q: "87) Что собой представляет элемент управления ComboBox?[span_301](end_span)[span_302](start_span)", o: ["это окно, куда выводится список...[span_302](end_span)[span_303](start_span)", "это элемент управления, позволяющий пользователю выбрать значение, а так же ввести данные, отсутствующие в списке;[span_303](end_span)"], a: 1 },
    [span_304](start_span){ q: "88) Что собой представляет элемент управления ToggleButton?[span_304](end_span)[span_305](start_span)", o: ["этот элемент управления определяет кнопки с фиксацией и используется для выбора не взаимоисключающих вариантов (если этих вариантов немного);[span_305](end_span)[span_306](start_span)", "этот элемент управления позволяет создавать на форме несколько страниц...[span_306](end_span)"], a: 0 },
    [span_307](start_span){ q: "89) Какое действие реализует оператор MsgBox?[span_307](end_span)[span_308](start_span)", o: ["осуществляет вывод на экран монитора значений величин, указанных в списке вывода;[span_308](end_span)[span_309](start_span)", "осуществляет вывод в ячейки таблицы Excel значений величин...[span_309](end_span)"], a: 0 },
    [span_310](start_span){ q: "90) Какое действие реализует оператор InputBox?[span_310](end_span)[span_311](start_span)", o: ["осуществляет ввод c экрана монитора значений величин, указанных в списке ввода;[span_311](end_span)[span_312](start_span)", "осуществляет вывод на экран монитора значений величин...[span_312](end_span)"], a: 0 }
];

let score = 0;
let currentQuestionIndex = 0;
let selectedQuestions = [];

function initQuiz() {
    score = 0;
    currentQuestionIndex = 0;
    document.getElementById('start-container').style.display = 'none';
    document.getElementById('result-container').style.display = 'none';
    document.getElementById('quiz-container').style.display = 'block';

    let shuffledQuestions = [...allQuestions].sort(() => 0.5 - Math.random());
    selectedQuestions = shuffledQuestions.slice(0, 40);

    selectedQuestions.forEach(q => {
        let opts = q.o.map((text, i) => ({ text, isCorrect: i === q.a }));
        opts.sort(() => 0.5 - Math.random());
        q.options = opts;
    });

    renderQuestion();
}

function renderQuestion() {
    if (currentQuestionIndex >= selectedQuestions.length) {
        showResult();
        return;
    }

    const q = selectedQuestions[currentQuestionIndex];
    document.getElementById('q-num').innerText = `Вопрос ${currentQuestionIndex + 1} из 40`;
    document.getElementById('score-live').innerText = `Счет: ${score}`;
    document.getElementById('question-text').innerText = q.q;

    const optsContainer = document.getElementById('options-container');
    optsContainer.innerHTML = '';

    q.options.forEach(opt => {
        const btn = document.createElement('button');
        btn.innerText = opt.text;
        btn.onclick = () => handleAnswer(opt.isCorrect);
        optsContainer.appendChild(btn);
    });
}

function handleAnswer(isCorrect) {
    if (isCorrect) score++;
    currentQuestionIndex++;
    renderQuestion();
}

function showResult() {
    document.getElementById('quiz-container').style.display = 'none';
    document.getElementById('result-container').style.display = 'block';
    document.getElementById('score-final').innerText = `Ваш результат: ${score} из 40`;
}
